import { Photo } from "@/lib/types";
import { Timestamp } from "firebase/firestore";

// Демо-фотографії для тестування UI без Firebase
// Використовуємо picsum.photos для placeholder зображень
export const MOCK_PHOTOS: Photo[] = [
    {
        id: "demo_1",
        url: "https://picsum.photos/seed/family1/1200/800",
        thumbnailUrl: "https://picsum.photos/seed/family1/400/267",
        name: "Літній відпочинок 1995",
        description: "Родинний відпочинок на морі, Одеса",
        tags: ["відпочинок", "море", "літо", "1995"],
        dateTaken: Timestamp.fromDate(new Date("1995-07-15")),
        uploadedBy: "demo@family.com",
    },
    {
        id: "demo_2",
        url: "https://picsum.photos/seed/family2/800/1200",
        thumbnailUrl: "https://picsum.photos/seed/family2/267/400",
        name: "День народження бабусі",
        description: "80-річчя бабусі Марії",
        tags: ["день народження", "бабуся", "свято", "2000"],
        dateTaken: Timestamp.fromDate(new Date("2000-03-20")),
        uploadedBy: "demo@family.com",
    },
    {
        id: "demo_3",
        url: "https://picsum.photos/seed/family3/1200/900",
        thumbnailUrl: "https://picsum.photos/seed/family3/400/300",
        name: "Новий рік 2005",
        description: "Святкування Нового року всією родиною",
        tags: ["новий рік", "свято", "зима", "2005"],
        dateTaken: Timestamp.fromDate(new Date("2005-01-01")),
        uploadedBy: "demo@family.com",
    },
    {
        id: "demo_4",
        url: "https://picsum.photos/seed/family4/1000/1000",
        thumbnailUrl: "https://picsum.photos/seed/family4/400/400",
        name: "Весілля",
        description: "Весілля тітки Олі та дядька Миколи",
        tags: ["весілля", "свято", "родина", "1998"],
        dateTaken: Timestamp.fromDate(new Date("1998-09-12")),
        uploadedBy: "demo@family.com",
    },
    {
        id: "demo_5",
        url: "https://picsum.photos/seed/family5/1200/700",
        thumbnailUrl: "https://picsum.photos/seed/family5/400/233",
        name: "Шкільна лінійка",
        description: "Перший день у школі, 1 вересня",
        tags: ["школа", "діти", "вересень", "2003"],
        dateTaken: Timestamp.fromDate(new Date("2003-09-01")),
        uploadedBy: "demo@family.com",
    },
    {
        id: "demo_6",
        url: "https://picsum.photos/seed/family6/900/1200",
        thumbnailUrl: "https://picsum.photos/seed/family6/300/400",
        name: "Великдень у бабусі",
        description: "Великодній стіл, писанки та паска",
        tags: ["великдень", "бабуся", "свято", "2010"],
        dateTaken: Timestamp.fromDate(new Date("2010-04-04")),
        uploadedBy: "demo@family.com",
    },
    {
        id: "demo_7",
        url: "https://picsum.photos/seed/family7/1200/800",
        thumbnailUrl: "https://picsum.photos/seed/family7/400/267",
        name: "Карпати",
        description: "Похід у Карпати всією сімʼєю",
        tags: ["карпати", "гори", "похід", "2015"],
        dateTaken: Timestamp.fromDate(new Date("2015-08-20")),
        uploadedBy: "demo@family.com",
    },
    {
        id: "demo_8",
        url: "https://picsum.photos/seed/family8/1100/800",
        thumbnailUrl: "https://picsum.photos/seed/family8/400/290",
        name: "Випускний",
        description: "Випускний вечір у школі",
        tags: ["випускний", "школа", "свято", "2012"],
        dateTaken: Timestamp.fromDate(new Date("2012-06-25")),
        uploadedBy: "demo@family.com",
    },
    {
        id: "demo_9",
        url: "https://picsum.photos/seed/family9/800/1100",
        thumbnailUrl: "https://picsum.photos/seed/family9/290/400",
        name: "Хрещення",
        description: "Хрещення маленького Данилка",
        tags: ["хрещення", "церква", "свято", "2018"],
        dateTaken: Timestamp.fromDate(new Date("2018-05-15")),
        uploadedBy: "demo@family.com",
    },
    {
        id: "demo_10",
        url: "https://picsum.photos/seed/family10/1200/800",
        thumbnailUrl: "https://picsum.photos/seed/family10/400/267",
        name: "Різдво 2020",
        description: "Святвечір у колі родини",
        tags: ["різдво", "свято", "зима", "2020"],
        dateTaken: Timestamp.fromDate(new Date("2020-12-25")),
        uploadedBy: "demo@family.com",
    },
    {
        id: "demo_11",
        url: "https://picsum.photos/seed/family11/1000/750",
        thumbnailUrl: "https://picsum.photos/seed/family11/400/300",
        name: "Дитячі роки",
        description: "Старе фото з дитинства, аналогова плівка",
        tags: ["дитинство", "ретро", "плівка", "1988"],
        dateTaken: Timestamp.fromDate(new Date("1988-06-10")),
        uploadedBy: "demo@family.com",
    },
    {
        id: "demo_12",
        url: "https://picsum.photos/seed/family12/1200/900",
        thumbnailUrl: "https://picsum.photos/seed/family12/400/300",
        name: "Сімейний обід",
        description: "Недільний обід у дідуся та бабусі",
        tags: ["обід", "родина", "неділя", "2022"],
        dateTaken: Timestamp.fromDate(new Date("2022-03-06")),
        uploadedBy: "demo@family.com",
    },
];
